### ISSUE TITLE
remove() not working properly

### ISSUE THREAD

**Issue by ajeun** [wearefractal/glob-watcher#16]
If you look in the gaze source code, you need to pass an argument for the path to remove to the watcher.remove() function. Right now you aren't passing any arguments so it does nothing.

**Comment by contra** [comment]
PR?

**Comment by ajeun** [comment]
What does PR stand for?

**Comment by heikki** [comment]
[Contributing to Open Source on GitHub](https://guides.github.com/activities/contributing-to-open-source/#contributing) -> Pull Request
