### ISSUE TITLE
Licensing issue with included library

### ISSUE THREAD

**Issue by mmucklo** [wearefractal/glob-watcher#20]
Installing gaze installs a bunch of other packages, at least one of which has no license.

Here's an example:

gaze 0.5.1 requires globule ~0.1.0
globule ~0.1.0 requires glob ~3.1.21
glob 3.1.21 requires inherits 1

inherits 1.0.0 has just a README.md with no license specified, neither in the inherits.js file, nor in the README.md, nor in the package.json file.  The repo itself on github.com has no tag for 1.0.0 either.

This is a problem with an organization that's perhaps concerned about making sure everything is licensed properly.

In tracing this back, it seems that if glob-watcher were to require gaze 0.6.4, it may fix the problem.  At least inherits 2 would be required.

**Comment by phated** [comment]
We won't be able to switch this in the 3.x branch of gulp, as it will be a breaking change.  If you are just looking for a library that watches glob, I highly suggest chokidar (which gulp will be switching to in 4.0)

**Comment by mmucklo** [comment]
Ok - unfortunately that makes glob-watcher (and it's ultimate dependent, gulp 3.x) off limits for me for a certain project I'm working on.  Maybe after the 4.0 release.

Thanks for the reply,
Matt

**Comment by contra** [comment]
@mmucklo Why not open an issue on the inherits module or the glob module that depends on inherits? Not sure why we got brought into this. This can all be rectified by either glob or inherits publishing a patch release that corrects it, then gulp 3.x will get it

**Comment by mmucklo** [comment]
So inherits has a version 2 with a license.

glob 3.2.7 uses inherits 2
globule 0.2.0 uses glob 3.2.7
gaze 0.6.4 uses globule 0.2.0

Everyone else in the chain below glob-watcher has already upgraded.

   glob-watcher has not.

This issue then makes gulp 3.x and it's dependency chain out of date as well since it (ultimately) depends on glob-watcher.

**Comment by phated** [comment]
@mmucklo like @contra said, just have inherits publish a 1.0.1, which will automatically get picked up by our modules due to semver.  There's absolutely no reason we have to adopt breaking changes (major semver bump) to get a license update.

**Comment by mmucklo** [comment]
Okay just did, but, BTW gaze 0.6.4 vs 0.5.1 is only a minor semver bump.

I'm not sure if you directly use the inherits 1 pulled in by glob 3.1.x.

If you do I understand, but if not, then consider that the other packages are only minor semver bumps, not major ones.  Nevertheless if https://github.com/isaacs/inherits/issues/18 gets resolved, it's a moot issue.

**Comment by contra** [comment]
@mmucklo gaze 0.6.x is horribly broken so we can't and won't update to that

**Comment by mmucklo** [comment]
So instead of fixing your dependency as initially requested, which probably would have been wiser for all of us involved, you asked me to contact the owner of inherits.

I did as I was asked, and per the request he published a 1.0.1.

However, you may want to have a look at https://github.com/isaacs/inherits/issues/18 to see how it was done.

**Comment by contra** [comment]
@mmucklo Please enlighten me since we are all so dumb and you are so smart: which dependency should we have updated to correct this problem?

**Comment by mmucklo** [comment]
As much as I hate dealing with licensing issues, I'm however charged to have to deal with these things.  I'm sorry and I apologize for troubling you.

I'm probably at least as annoyed at having to deal with this as you all are in having to waste your time dealing with such an absurd issue as someone filing an issue over a lack of a license file included by a bundle that you seem to have no control over other than upgrade to a "horribly broken" version of gaze.

Therefore my last comment was in haste (not fully understanding the gaze issue), and presumed that something could be done, when in fact, as @contra's previous comment correctly points out, it's a real catch-22.  For that I also do apologize.

The only other possible solutions I see are to cut ties with gaze, push gaze to fix the 0.6.x branch, or assume gaze plus it's dependencies into your own code base and patch them yourself, all of which probably seem to be sub-optimal compared to a simple update of inherits 1.

That I troubled you at all was solely through tracing the dependency chain and finding all other bundles deeper than glob-watcher had updated, it just seemed to be glob-watcher that was holding inherits at 1, again not knowing that gaze 0.6.x was broken, which you have so enlightened me to the problem.

Anyway I will try to plead with the owner of inherits to see if a more workable solution to inherits 1 can be made.

**Comment by contra** [comment]
@mmucklo We are already moving away from gaze in gulp 4.0 in favor of chokidar, but this is a breaking change and won't land in 3.x so it won't solve your problem.

**Comment by mmucklo** [comment]
According to my tests and notes https://github.com/isaacs/inherits/issues/18 - this is now resolved
