### ISSUE TITLE
Update to gaze 0.5

### ISSUE THREAD

**Issue by yocontra** [wearefractal/glob-watcher#4]
This will fix CPU issues, files going missing, new stuff not being watched, etc.

**Comment by eranimo** [comment]
Any update on this?

**Comment by heikki** [comment]
https://github.com/wearefractal/glob-watcher/pull/13

**Comment by SparrowAvanade** [comment]
@shama +1 for the "sometimes a pattern can accidentally match the node_modules folder".

I had a glob starting with `"**/` so it was most certainly picking up both `node_modules` and `bower_components`.  CPU down from ~30% to ~1% including increasing interval to 1000ms.

**Comment by RopoMen** [comment]
@SparrowAvanade thanks for the note! This resolved issue for me.
